### ISSUE TITLE
No PyPI package supporting Python 3

### ISSUE THREAD

**Issue by kralca** [STIXProject/stix-ramrod#10]
Hi there. Do you have any plans to create a PyPI package that works with Python 3?

**Comment by gtback** [comment]
Hi @kralca. The current packages on PyPI are source distributions, so should be agnostic to Python 2 or Python 3. That said, the code itself hasn't been updated in a while, but Travis-CI runs tests on Python 3.3, 3.4, and 3.5, so I would expect it to work under Python 3. 

If you're having errors when running ramrod on Python 3, please let us know!

**Comment by kralca** [comment]
Hi @gtback, thanks for getting back to me. All works fine in Python 3 when I install using the most recent code in the master branch. However, the PyPI version doesn't appear to have been updated for quite some time.

```
$ python -V
Python 3.5.2
$ pip -V
pip 9.0.1 from /<redacted>/lib/python3.5/site-packages (python 3.5)
$ pip install stix-ramrod
Collecting stix-ramrod
  Downloading stix-ramrod-1.1.0.zip (71kB)
    100% |████████████████████████████████| 81kB 847kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4m/j7sv7p3x4t3cbt1cwlzds9tw0000gp/T/pip-build-kc73v4wh/stix-ramrod/setup.py", line 26, in <module>
        raise Exception('stix-ramrod required Python 2.6/2.7')
    Exception: stix-ramrod required Python 2.6/2.7
```

Am I missing something?

**Comment by gtback** [comment]
Oh wow, thanks. Sorry, I hadn't realized we never tagged and pushed a new release to PyPI. I'll take care of that this week.

**Comment by clenk** [comment]
A new version has been released to PyPI. Thanks, @kralca!
