### ISSUE TITLE
No support for converting packages with "STIX_Packages" root node

### ISSUE THREAD

**Issue by johnmccash** [STIXProject/stix-ramrod#4]
I just tried to convert a STIX 1.0 package (obtained from FS_ISAC) which has a "STIX_Packages" root node. I get the following error:

[!] Update Error: Document root node must be one of ['Observables', 'STIX_Package']. Found: 'STIX_Packages'

Thanks

**Comment by bworrell** [comment]
Hi @johnmccash, thanks for the issue! The `STIX_Packages` element is not a valid STIX root-level element and will not validate against the STIX schemas. The `stix-ramrod` library supports the processing of CybOX `Observables` and STIX `STIX_Package` instance documents, which are referred to in that error message.

Is it possible to extract the `STIX_Package` elements from the `STIX_Packages` collection? If so, you could then update them iteratively.

**Comment by bworrell** [comment]
I am going to close this out since the error is the result of passing a non-STIX/CybOX document into stix-ramrod. I can reopen it if we want to discuss this more in the future. Thanks!

**Comment by johnmccash** [comment]
Bryan
                I’m not sure, but I thought this element was actually legal in 1.0, but was deprecated in 1.1. It may be that it was part of a prerelease version of 1.0 which was on Github, and so was used by some people in error. In any case, it’s no longer an issue for me. I was trying to convert an old indicator dump, for which I now have a more recent update that does not include the offending element.
                                Thanks
                                                John
